import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

const EXPORTED = ["Tilt", "MockPyth"] as const;

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  tilt: string;
  pyth: string;
  treasury: string;
  feeBps: number;
  durations: number[];
  assets: string[];
  deployedAt: string;
  txHash: string | null;
};

/**
 * Writes each exported contract's ABI to ../src/lib/abi/<Name>.abi.json (for
 * tooling) and to <name>.ts as an `as const` tuple, so viem/wagmi infer the
 * argument and return types of every call the site makes.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    const json = JSON.stringify(artifact.abi, null, 2);
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.abi.json`), json + "\n");
    const ident = name[0].toLowerCase() + name.slice(1) + "Abi";
    fs.writeFileSync(
      path.join(frontendAbiDir, `${name[0].toLowerCase() + name.slice(1)}.ts`),
      `// Generated by contracts/scripts/lib/exportAbi.ts on every \`hardhat compile\` — do not edit.\nexport const ${ident} = ${json} as const;\n`,
    );
  }
}
